### ISSUE TITLE
[Bug 🐞]: Syncing Frequently Pauses

### ISSUE THREAD

**Issue by Alexhuszagh** [davidsmorais/kuro#35]
# Bug Title 🐞

**Describe the bug**
When using Kuro for a long period, it frequently says "Your changes were saved but syncing is paused. Refresh this page to sync your changes." However, clicking refresh does not sync the changes, and only logging out and logging back in (or rebooting) seems to refresh syncing.

**Reproduction Steps**
1. Use Kuro for a long period (I believe on multiple devices as well).

**Expected Behavior**
Syncing should not break, even over long sessions.

**Screenshots**
![Syncing Issue](https://user-images.githubusercontent.com/9440903/170715701-b56decf1-736c-4101-826b-d481ca992cce.png)

**Technical Info (please complete the following information)**
 - OS: Fedora 36
 - Kuro Version: 8.1.0

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Thanks for reporting @Alexhuszagh

I've been praying to reproduce this for 2 days now and I never get this pop up message :cry: 

How long would you say you leave Kuro open before this message pops ?

**Comment by davidsmorais** [comment]
> I'll see if I can get a more reproducible test case, because I understand this is very much like finding a needle in a haystack (and very difficult for you, as a maintainer, to fix until then).

And the fact that I'm 98% sure that this is on To-Do's web client managed my Microsft themselves :upside_down_face:

**Comment by Alexhuszagh** [comment]
Just wondering: has this been patched or is this still an upstream issue?

**Comment by davidsmorais** [comment]
I've closed it because: 
- No activity in the issue, assumed it was fixed in 8.1.3
- From your screenshot, this looks like something happening on Microsoft's side and there's not much I can to here...

**Comment by Alexhuszagh** [comment]
Can you re-open this then and add an upstream label, signifying that there's nothing to be done but waiting on Microsoft to fix their end? Because this is still an issue I believe (my laptop is currently in the shop, so I can't test it currently).

**Comment by davidsmorais** [comment]
Yeah, makes sense to leave this as a future heads up for other users and to avoid repeated issues 

Done :heavy_check_mark:
