### ISSUE TITLE
[Bug 🐞]: Wrong theme on notifications 

### ISSUE THREAD

**Issue by tvarsis** [davidsmorais/kuro#54]
# Bug Title 🐞

**Describe the bug**
Notifications are white and text on them are light grey (hard to see). They also appear behind the new task input bar. I don't know if this is some strange interaction with KDE or if this is happening everywhere.

**Expected Behavior**
Notifications to follow selected theme in Kuro and to appear over the new task input bar.

**Screenshots**
Here you can see a screenshot of the issue. I have blurred out the text of the task/notification, but you should get the idea.
![image](https://user-images.githubusercontent.com/10090010/182182139-2cb4beca-2496-4cc2-a29f-d752ad93c175.png)

**Technical Info (please complete the following information)**
 - OS: OpenSUSE Tumbleweed with KDE 5.25.3
 - Kuro Version: 8.1.4

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Thank, I'll try and fix this in the next version

**Comment by davidsmorais** [comment]
![image](https://user-images.githubusercontent.com/22729436/188506484-d4d2f5a7-6f00-44b3-984a-b02128571923.png)
fixed and gave it a cool new look

**Comment by tvarsis** [comment]
@davidsmorais Thanks for this, but I'm still seeing the same issue even after upgrading to 8.1.5:
![image](https://user-images.githubusercontent.com/10090010/188625243-fe1c3b80-9f77-4611-af3d-ee302b398969.png)

**Comment by davidsmorais** [comment]
That is indeed weird. 
Just to be sure:
you're triggering the notifications by using the 'Remind me' feature on ToDo, right ?

**Comment by tvarsis** [comment]
@davidsmorais I completely removed all versions/appimages of Kuro, and reinstalled 8.1.5 and then it worked fine. My bad!
![image](https://user-images.githubusercontent.com/10090010/188652235-ee2c0ed7-cdc5-4a20-8ddb-94afe3880467.png)

Thanks for fixing this!
